tide:
  image: "gcr.io/k8s-prow/tide:latest"
  sync_period: "30s"
  status_update_period: "30s"
  merge_method:
    kravch3nko/test-tide-merge-queue: rebase
  squash_label: ""
  blocker_label: "merge-queue/stop"
  queries:
  - repos:
    - kravch3nko/test-tide-merge-queue
    labels:
    - "merge-queue/add"
    missingLabels: []
  max_goroutines: 20

github:
  secret_name: "github-token"
  orgs:
  - name: kravch3nko
    repos:
    - name: test-tide-merge-queue
