github:
  tokenSecretName: "github-token"

# Tide configuration
tide:
  image: "gcr.io/k8s-prow/tide:latest"
  config:
    sync_period: "30s"
    status_update_period: "30s"
    batch_size_limit: 1  # Disables batching
    max_goroutines: 20

    blocker_label: "merge-queue/stop"
    
    merge_method:
      kravch3nko/test-tide-merge-queue: squash

    queries:
      - repos:
          - kravch3nko/test-tide-merge-queue
        labels:
          - merge-queue/add
        missingLabels: []                 
        includeDrafts: false

  