apiVersion: v1
kind: ConfigMap
metadata:
  name: prow-config
  namespace: prow
data:
  config.yaml: |
    tide:
      merge_method:
        {{ .Values.github.org }}/{{ .Values.github.repo }}: {{ .Values.tide.mergeMethod }}
      queries:
      - repos:
        - {{ .Values.github.org }}/{{ .Values.github.repo }}
        labels:
        {{- range .Values.tide.requiredLabels }}
        - {{ . }}
        {{- end }}
        missingLabels:
        {{- range .Values.tide.missingLabels }}
        - {{ . }}
        {{- end }}
    github:
      orgs:
      - name: {{ .Values.github.org }}