apiVersion: v1
kind: ConfigMap
metadata:
  name: prow-config
  namespace: prow
data:
  config.yaml: |
    tide:
{{ toYaml .Values.tide | indent 6 }}
    github:
{{ toYaml .Values.github | indent 6 }}
