apiVersion: v1
kind: ConfigMap
metadata:
  name: prow-config
  namespace: prow
data:
  config.yaml: |
    tide:
      sync_period: "30s"
      status_update_period: "30s"
      
      {{- /* Determine repository configuration */ -}}
      {{- $repoList := list }}
      {{- if .Values.repositories }}
        {{- /* New multi-repo format */ -}}
        {{- $repoList = .Values.repositories }}
      {{- else if .Values.env.GITHUB_ORG }}
        {{- /* Single repo from env vars */ -}}
        {{- $repo := dict "org" (.Values.env.GITHUB_ORG) "name" (.Values.env.GITHUB_REPO | default .Values.github.repo) }}
        {{- if .Values.env.CI_STATUS_CHECKS }}
          {{- $repo = set $repo "ciStatusChecks" (splitList "," .Values.env.CI_STATUS_CHECKS) }}
        {{- else }}
          {{- $repo = set $repo "ciStatusChecks" .Values.tide.defaultCiStatusChecks }}
        {{- end }}
        {{- $repoList = list $repo }}
      {{- else }}
        {{- /* Legacy single repo format */ -}}
        {{- $repo := dict "org" .Values.github.org "name" .Values.github.repo "ciStatusChecks" .Values.tide.defaultCiStatusChecks }}
        {{- $repoList = list $repo }}
      {{- end }}
      
      merge_method:
        {{- range $repoList }}
        {{ .org }}/{{ .name }}: {{ $.Values.tide.mergeMethod }}
        {{- end }}
      squash_label: ""
      blocker_label: "merge-queue/stop"
      
      queries:
      {{- /* Generate separate query for each repository to handle different CI checks */ -}}
      {{- range $repoList }}
      {{- $repoName := printf "%s/%s" .org .name }}
      {{- $ciChecks := .ciStatusChecks | default $.Values.tide.defaultCiStatusChecks }}
      
      # High Priority for {{ $repoName }}
      - repos:
        - {{ $repoName }}
        labels:
        - "merge-queue/add-high"
        missingLabels: []
        requiredStatusChecks:
        {{- range $ciChecks }}
        - {{ . }}
        {{- end }}
        includeDrafts: false
      
      # Normal Priority for {{ $repoName }}
      - repos:
        - {{ $repoName }}
        labels:
        - "merge-queue/add"
        missingLabels: []
        requiredStatusChecks:
        {{- range $ciChecks }}
        - {{ . }}
        {{- end }}
        includeDrafts: false
      {{- end }}
      
      context_options:
        {{- $allCiChecks := list }}
        {{- range $repoList }}
          {{- $ciChecks := .ciStatusChecks | default $.Values.tide.defaultCiStatusChecks }}
          {{- range $ciChecks }}
            {{- if not (has . $allCiChecks) }}
              {{- $allCiChecks = append $allCiChecks . }}
            {{- end }}
          {{- end }}
        {{- end }}
        {{- range $allCiChecks }}
        {{ . }}:
          description: "CI check: {{ . }}"
          required: true
        {{- end }}
      
      max_goroutines: 20
      
    github:
      orgs:
      {{- $orgMap := dict }}
      {{- range $repoList }}
        {{- if not (hasKey $orgMap .org) }}
          {{- $orgMap = set $orgMap .org (list) }}
        {{- end }}
        {{- $repos := index $orgMap .org }}
        {{- $repos = append $repos .name }}
        {{- $orgMap = set $orgMap .org $repos }}
      {{- end }}
      {{- range $org, $repos := $orgMap }}
      - name: {{ $org }}
        repos:
        {{- range $repos }}
        - name: {{ . }}
        {{- end }}
      {{- end }}