apiVersion: v1
kind: Service
metadata:
  name: ghproxy
  namespace: prow
spec:
  selector:
    app: ghproxy
  ports:
  - port: 80
    targetPort: 8888
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghproxy
  namespace: prow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghproxy
  template:
    metadata:
      labels:
        app: ghproxy
    spec:
      containers:
      - name: ghproxy
        image: gcr.io/k8s-prow/ghproxy:latest
        args:
        - --cache-dir=/cache
        - --cache-sizeGB=1
        - --serve-metrics=true
        - --legacy-disable-disk-cache-partitions-by-auth-header=false
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: cache
          mountPath: /cache
      volumes:
      - name: cache
        emptyDir: {} 