apiVersion: v1
kind: ServiceAccount
metadata:
  name: tide
  namespace: prow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prow
  name: tide
rules:
- apiGroups: ["prow.k8s.io"]
  resources: ["prowjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tide
rules:
- apiGroups: ["prow.k8s.io"]
  resources: ["prowjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tide
  namespace: prow
subjects:
- kind: ServiceAccount
  name: tide
  namespace: prow
roleRef:
  kind: Role
  name: tide
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tide
subjects:
- kind: ServiceAccount
  name: tide
  namespace: prow
roleRef:
  kind: ClusterRole
  name: tide
  apiGroup: rbac.authorization.k8s.io 