apiVersion: v1
kind: Service
metadata:
  name: hook
  namespace: prow
spec:
  ports:
  - port: 80
    targetPort: 8888
  selector:
    app: hook
---
apiVersion: v1
kind: Service
metadata:
  name: deck
  namespace: prow
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: deck
