name: CI Simulation

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Simulate tests
        run: |
          echo "Running tests..."
          sleep 5
          echo "Tests passed!"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Simulate linting (50% failure rate)
        run: |
          echo "Running linter..."
          sleep 3
          # 50% chance of failure
          if [ $((RANDOM % 2)) -eq 0 ]; then
            echo "❌ Linting failed!"
            exit 1
          else
            echo "✅ Linting passed!"
          fi

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Simulate build
        run: |
          echo "Building..."
          sleep 4
          echo "Build successful!" 