name: Merge Queue Notifications

on:
  issues:
    types: [labeled, unlabeled]
  pull_request:
    types: [labeled, unlabeled]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    if: contains(github.event.label.name, 'merge-queue/stop')
    
    steps:
    - name: Queue Stopped Notification
      if: github.event.action == 'labeled'
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        custom_payload: |
          {
            "text": "🚨 MERGE QUEUE STOPPED",
            "attachments": [
              {
                "color": "danger",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}",
                    "short": true
                  },
                  {
                    "title": "Stopped by",
                    "value": "${{ github.event.sender.login }}",
                    "short": true
                  },
                  {
                    "title": "PR/Issue",
                    "value": "<${{ github.event.pull_request.html_url || github.event.issue.html_url }}|#${{ github.event.pull_request.number || github.event.issue.number }}>",
                    "short": true
                  },
                  {
                    "title": "Time",
                    "value": "<!date^${{ github.event.pull_request.updated_at || github.event.issue.updated_at }}^{date_short_pretty} at {time}|${{ github.event.pull_request.updated_at || github.event.issue.updated_at }}>",
                    "short": true
                  }
                ],
                "footer": "All merging is paused except critical PRs. Remove the label to resume."
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Queue Resumed Notification  
      if: github.event.action == 'unlabeled'
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        custom_payload: |
          {
            "text": "✅ MERGE QUEUE RESUMED",
            "attachments": [
              {
                "color": "good",
                "fields": [
                  {
                    "title": "Repository", 
                    "value": "${{ github.repository }}",
                    "short": true
                  },
                  {
                    "title": "Resumed by",
                    "value": "${{ github.event.sender.login }}",
                    "short": true
                  },
                  {
                    "title": "PR/Issue",
                    "value": "<${{ github.event.pull_request.html_url || github.event.issue.html_url }}|#${{ github.event.pull_request.number || github.event.issue.number }}>",
                    "short": true
                  },
                  {
                    "title": "Time",
                    "value": "<!date^${{ github.event.pull_request.updated_at || github.event.issue.updated_at }}^{date_short_pretty} at {time}|${{ github.event.pull_request.updated_at || github.event.issue.updated_at }}>",
                    "short": true
                  }
                ],
                "footer": "Normal merge queue operations have resumed."
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 