name: Rebase Merge Queue
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, labeled]

jobs:
  rebase:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.label.name == 'merge-queue/add')
    strategy:
      matrix:
        repo: ['test-tide-merge-queue']  # Just repo names without owner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          repositories: ${{ matrix.repo }}

      - name: Check stop label
        id: check
        run: |
          issues=$(curl -s -H "Authorization: Bearer ${{ steps.generate-token.outputs.token }}" \
            "https://api.github.com/repos/kravch3nko/${{ matrix.repo }}/issues?labels=merge-queue/stop&state=open" | jq '. | length')
          echo "blocked=$([[ $issues -gt 0 ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      - name: Rebase PRs
        if: steps.check.outputs.blocked != 'true'
        uses: peter-evans/rebase@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: kravch3nko/${{ matrix.repo }}
          include-labels: merge-queue/add
          base: main