name: Rebase Merge Queue
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, labeled]

jobs:
  rebase:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.label.name == 'merge-queue/add')
    runs-on: ubuntu-latest
    steps:
      - name: Check stop label
        id: check
        run: |
          IFS='/' read -r owner repo <<< "kravch3nko/test-tide-merge-queue"
          issues=$(curl -s -H "Authorization: Bearer ${{ secrets.PAT }}" \
            "https://api.github.com/repos/$owner/$repo/issues?labels=merge-queue/stop&state=open" | jq '. | length')
          echo "blocked=$([[ $issues -gt 0 ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      - name: Rebase PRs
        if: steps.check.outputs.blocked != 'true'
        uses: peter-evans/rebase@v3
        with:
          token: ${{ secrets.PAT }}
          repository: kravch3nko/test-tide-merge-queue
          include-labels: merge-queue/add
          base: main