name: Rebase Merge Queue
on:
  push:
    branches: [main]

# Add permissions for GITHUB_TOKEN
permissions:
  contents: write
  issues: read
  pull-requests: write

jobs:
  rebase:
    strategy:
      matrix:
        repo: ['kravch3nko/test-tide-merge-queue']
    runs-on: ubuntu-latest
    steps:
      # First check if rebase is allowed
      - name: Check stop label
        id: check
        run: |
          IFS='/' read -r owner repo <<< "${{ matrix.repo }}"
          issues=$(curl -s -H "Authorization: Bearer ${{ github.token }}" \
            "https://api.github.com/repos/$owner/$repo/issues?labels=merge-queue/stop&state=open" | jq '. | length')
          echo "blocked=$([[ $issues -gt 0 ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      # Find and rebase PRs if not blocked
      - name: Rebase PRs
        if: steps.check.outputs.blocked != 'true'
        uses: peter-evans/rebase@v3
        with:
          token: ${{ github.token }}
          repository: ${{ matrix.repo }}
          include-labels: merge-queue/add
          base: main